# SVM evaluation config for lejepa_line_helminth-eggs_split_2_pct_5_model_xavier
# wandb_run_id: 1ruhrpol
experiment:
  wandb_run_id: 1ruhrpol
  name: lejepa_line_helminth-eggs_split_2_pct_5_model_xavier
  dataset_name: helminth-eggs
  split_id: 2
  percentage: 5
  initialization_type: xavier
  num_classes: 9

svm:
  kernel: linear
  C: 100.0
  gamma: auto
  degree: 3
  max_iter: 10000
  coef0: 0
  decision_function_shape: ovo

evaluation:
  image_size: 200
  batch_size: 32
  num_workers: 4
  loader: ift_lab
