run_id: v15dvoqv
experiment_name: line_p25_flim
dataset_name: parasito
split: 1
percentage: 25
initialization_type: flim
freeze_encoder: false
max_epochs: 1000
patience: 50
lr: 0.001
weight_decay: 0.0001
batch_size: 32
hidden_dim: 256
dropout: 0.3
